import {
  Router,
  Network,
  Server,
  Camera,
  Monitor,
  HardDrive,
  Database,
  Wifi,
  WifiOff,
  Globe,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Cloud,
  CloudOff,
  Laptop,
  Smartphone,
  Printer,
  Cpu,
  CircuitBoard,
  Cable,
  Radio,
  Activity,
  Radar,
  Building,
  MapPin,
  Boxes,
  Plug,
  Usb,
  Webhook,
  HelpCircle
} from "lucide-react";

export const ICON_LIBRARY = {
  router: Router,
  switch: Network,
  network: Network,
  server: Server,
  camera: Camera,
  pc: Monitor,
  storage: HardDrive,
  database: Database,
  wifi: Wifi,
  wifi_off: WifiOff,
  globe: Globe,
  firewall: Shield,
  security: ShieldCheck,
  alert: ShieldAlert,
  cloud: Cloud,
  cloud_off: CloudOff,
  laptop: Laptop,
  mobile: Smartphone,
  printer: Printer,
  cpu: Cpu,
  board: CircuitBoard,
  cable: Cable,
  radio: Radio,
  activity: Activity,
  radar: Radar,
  building: Building,
  location: MapPin,
  rack: Boxes,
  plug: Plug,
  usb: Usb,
  webhook: Webhook
};

export const DefaultIcon = HelpCircle;